---
- name: Install software
  hosts: all
  become: yes

  vars:
    krita_version: 5.2.9

  tasks:
    - name: Add xournal++ ppa
      apt_repository:
        repo: ppa:apandada1/xournalpp-stable
        state: present

    # TODO: introduce a cached check so that if an update or upgrade has been done within the last hour, don't do that step
    - name: Update package list
      apt:
        update_cache: yes

    - name: Update packages to latest version
      apt:
        upgrade: dist

    - name: Install core tooling
      apt:
        state: present
        name:
          - build-essential
          - curl
          - cargo-1.76
          - direnv
          - fd-find
          - gh
          - git
          - jq
          - libfuse2 # required for older AppImage builds
          - python3
          - restic
          - ripgrep
          - rsync
          - sqlite3
          - syncthing
          - tmux
          - wget
          - zsh

    - name: Install Graphic Design Packaages
      apt:
        state: present
        name:
          - gimp
          - gimp-lensfun
          - gimp-plugin-registry
          - gimp-save-for-web
          - gpick
          - inkscape
          - xournalpp

    - name: Install Multimedia Packaages
      apt:
        state: present
        name:
          - audacity
          - clementine
          - obs-studio
          - vlc

    - name: Link fdfind to fd
      ansible.builtin.file:
        src: /usr/bin/fdfind
        dest: /usr/bin/fd
        state: link

    #
    # # TODO: This works, but it's slow. Find a way to test for a missing Krita installation and only run this if it's missing
    #
    # - name: Download Krita AppImage
    #   get_url:
    #     url: https://download.kde.org/stable/krita/{{ krita_version }}/krita-{{ krita_version }}-x86_64.appimage
    #     dest: /opt/krita-{{ krita_version }}-x86_64.AppImage
    #     mode: 0755
    # - name: Extract Krita AppImage
    #   ansible.builtin.shell: /opt/krita-{{ krita_version }}-x86_64.AppImage --appimage-extract
    #   args:
    #     chdir: /opt
    # - name: Move extracted Krita to /opt/krita-{{ krita_version }}
    #   ansible.builtin.shell: mv /opt/squashfs-root /opt/krita-{{ krita_version }}
    #   args:
    #     chdir: /opt
    # - name: Copy Krita Freedesktop Config
    #   ansible.builtin.copy:
    #     src: /opt/krita-{{ krita_version }}/org.kde.krita.desktop
    #     dest: /usr/share/applications/krita.desktop
    #     mode: 0644
    #     remote_src: true
    # - name: Copy Krita Icon
    #   ansible.builtin.copy:
    #     src: /opt/krita-{{ krita_version }}/krita.png
    #     dest: /opt/krita.png
    #     mode: 0644
    #     remote_src: true
    # - name: Update Krita Exec Path in Freedesktop Config
    #   ansible.builtin.replace:
    #     path: /usr/share/applications/krita.desktop
    #     regexp: 'Exec=krita %F'
    #     replace: 'Exec=/opt/krita-{{ krita_version }}-x86_64.AppImage %F'
    # - name: Update Krita Icon in Freedesktop Config
    #   ansible.builtin.replace:
    #     path: /usr/share/applications/krita.desktop
    #     regexp: 'Icon=krita'
    #     replace: 'Icon=/opt/krita.png'
    # - name: Add Krita to defaults.list
    #   ansible.builtin.lineinfile:
    #     path: /usr/share/applications/defaults.list
    #     line: image/krita=krita.desktop;
    #     create: yes
    # - name: Add Krita to mimeapps.list
    #   ansible.builtin.lineinfile:
    #     path: ~/.config/mimeapps.list
    #     line: image/krita=krita.desktop;
